/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ClienteDAO;
import model.Cliente;
import static util.DateChecker.DateChecker;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnPrincipal = new javax.swing.JPanel();
        jLtitle = new javax.swing.JLabel();
        jPnContato = new javax.swing.JPanel();
        jLcell = new javax.swing.JLabel();
        jTcelular = new javax.swing.JTextField();
        jLemail = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jLtele = new javax.swing.JLabel();
        jTtelefone = new javax.swing.JTextField();
        jPnDados = new javax.swing.JPanel();
        jLnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLCPF = new javax.swing.JLabel();
        jTcpf = new javax.swing.JTextField();
        jLRG = new javax.swing.JLabel();
        jTrg = new javax.swing.JTextField();
        jLnasc = new javax.swing.JLabel();
        jFTnascimento = new javax.swing.JFormattedTextField();
        jPnEndereco = new javax.swing.JPanel();
        jLendereco = new javax.swing.JLabel();
        jTendereco = new javax.swing.JTextField();
        jLbairro = new javax.swing.JLabel();
        jTbairro = new javax.swing.JTextField();
        jLcidade = new javax.swing.JLabel();
        jTcidade = new javax.swing.JTextField();
        jLUF = new javax.swing.JLabel();
        jCbEstado = new javax.swing.JComboBox();
        jBcadastrar = new javax.swing.JButton();

        setTitle("Cadastro de Clientes");

        jPnPrincipal.setBackground(new java.awt.Color(56, 56, 56));

        jLtitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLtitle.setText("TryFatus");
        jLtitle.setForeground(new Color(187,187,187));

        jPnContato.setBackground(new java.awt.Color(56, 56, 56));
        jPnContato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Contato", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new Font("Times New Roman", 1, 14), new Color(187,187,187)));

        jLcell.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLcell.setForeground(new Color(187,187,187));
        jLcell.setText("Celular:");

        jTcelular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTcelular.setBackground(new Color(69,73,74));
        jTcelular.setForeground(new Color(187, 187, 187));

        jLemail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLemail.setForeground(new Color(187,187,187));
        jLemail.setText("Email:");

        jTemail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTemail.setBackground(new Color(69,73,74));
        jTemail.setForeground(new Color(187, 187, 187));

        jLtele.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLtele.setForeground(new Color(187,187,187));
        jLtele.setText("Telefone:");

        jTtelefone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTtelefone.setBackground(new Color(69,73,74));
        jTtelefone.setForeground(new Color(187, 187, 187));

        javax.swing.GroupLayout jPnContatoLayout = new javax.swing.GroupLayout(jPnContato);
        jPnContato.setLayout(jPnContatoLayout);
        jPnContatoLayout.setHorizontalGroup(
            jPnContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPnContatoLayout.createSequentialGroup()
                        .addComponent(jLemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTemail))
                    .addGroup(jPnContatoLayout.createSequentialGroup()
                        .addComponent(jLtele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnContatoLayout.createSequentialGroup()
                        .addComponent(jLcell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcelular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnContatoLayout.setVerticalGroup(
            jPnContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLtele, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLcell, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLemail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnDados.setBackground(new java.awt.Color(56, 56, 56));
        jPnDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new Font("Times New Roman", 1, 14), new Color(187,187,187)));
        jPnDados.setForeground(new java.awt.Color(56, 56, 56));
        jPnDados.setToolTipText("");

        jLnome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLnome.setForeground(new Color(187,187,187));
        jLnome.setText("Nome:");

        jTnome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTnome.setSelectionColor(new java.awt.Color(0, 0, 0));
        jTnome.setBackground(new Color(69,73,74));
        jTnome.setForeground(new Color(187, 187, 187));

        jLCPF.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLCPF.setForeground(new Color(187,187,187));
        jLCPF.setText("CPF:");

        jTcpf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTcpf.setBackground(new Color(69,73,74));
        jTcpf.setForeground(new Color(187, 187, 187));

        jLRG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLRG.setForeground(new Color(187,187,187));
        jLRG.setText("RG:");

        jTrg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTrg.setBackground(new Color(69,73,74));
        jTrg.setForeground(new Color(187, 187, 187));

        jLnasc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLnasc.setForeground(new Color(187,187,187));
        jLnasc.setText("Nascimento:");

        jFTnascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            jFTnascimento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }

        jFTnascimento.setFont(new java.awt.Font("Times New Roman", 0, 14));

        jFTnascimento.setBackground(new Color(69,73,74));

        jFTnascimento.setForeground(new Color(187,187,187));

        javax.swing.GroupLayout jPnDadosLayout = new javax.swing.GroupLayout(jPnDados);
        jPnDados.setLayout(jPnDadosLayout);
        jPnDadosLayout.setHorizontalGroup(
            jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnDadosLayout.createSequentialGroup()
                        .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCPF)
                            .addComponent(jLnome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPnDadosLayout.createSequentialGroup()
                                .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLRG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTrg, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTnome)))
                    .addGroup(jPnDadosLayout.createSequentialGroup()
                        .addComponent(jLnasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPnDadosLayout.setVerticalGroup(
            jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLCPF)
                        .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnasc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnEndereco.setBackground(new java.awt.Color(56, 56, 56));
        jPnEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new Font("Times New Roman", 1, 14), new Color(187,187,187)));

        jLendereco.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLendereco.setForeground(new Color(187,187,187));
        jLendereco.setText("Endereço:");

        jTendereco.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTendereco.setBackground(new Color(69,73,74));
        jTendereco.setForeground(new Color(187, 187, 187));

        jLbairro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLbairro.setForeground(new Color(187,187,187));
        jLbairro.setText("Bairro:");

        jTbairro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTbairro.setBackground(new Color(69,73,74));
        jTbairro.setForeground(new Color(187, 187, 187));

        jLcidade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLcidade.setForeground(new Color(187,187,187));
        jLcidade.setText("Cidade:");

        jTcidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTcidade.setBackground(new Color(69,73,74));
        jTcidade.setForeground(new Color(187, 187, 187));

        jLUF.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLUF.setForeground(new Color(187,187,187));
        jLUF.setText("UF:");

        jCbEstado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCbEstado.setMaximumRowCount(13);
        jCbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCbEstado.setSelectedIndex(23);
        jCbEstado.setToolTipText("");

        javax.swing.GroupLayout jPnEnderecoLayout = new javax.swing.GroupLayout(jPnEndereco);
        jPnEndereco.setLayout(jPnEnderecoLayout);
        jPnEnderecoLayout.setHorizontalGroup(
            jPnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnEnderecoLayout.createSequentialGroup()
                        .addComponent(jLcidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcidade))
                    .addGroup(jPnEnderecoLayout.createSequentialGroup()
                        .addGroup(jPnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnEnderecoLayout.createSequentialGroup()
                                .addComponent(jLbairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLUF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnEnderecoLayout.createSequentialGroup()
                                .addComponent(jLendereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );
        jPnEnderecoLayout.setVerticalGroup(
            jPnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLendereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbairro)
                    .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLUF)
                    .addComponent(jCbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcidade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCbEstado.getAccessibleContext().setAccessibleName("");

        jBcadastrar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jBcadastrar.setText("Cadastrar");
        jBcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnPrincipalLayout = new javax.swing.GroupLayout(jPnPrincipal);
        jPnPrincipal.setLayout(jPnPrincipalLayout);
        jPnPrincipalLayout.setHorizontalGroup(
            jPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPnPrincipalLayout.createSequentialGroup()
                .addGroup(jPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPnDados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPnContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnPrincipalLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLtitle)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPnPrincipalLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jBcadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnPrincipalLayout.setVerticalGroup(
            jPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLtitle)
                .addGap(18, 18, 18)
                .addComponent(jPnDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPnEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcadastrar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrarActionPerformed
        // TODO add your handling code here:
        if (jTnome.getText().isEmpty() || jTcpf.getText().isEmpty() || jTrg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome, CPF e RG não podem estar vazios!", "Inane warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Cliente cliente = new Cliente();
            ClienteDAO dao = new ClienteDAO();
            cliente.setNome(jTnome.getText());
            cliente.setCPF(jTcpf.getText());
            cliente.setRG(jTrg.getText());
            cliente.setCelular(jTcelular.getText());
            cliente.setTelefone(jTtelefone.getText());
            cliente.setEmail(jTemail.getText());
            cliente.setEndereco(jTendereco.getText());
            cliente.setBairro(jTbairro.getText());
            cliente.setCidade(jTcidade.getText());
            cliente.setEstado(jCbEstado.getSelectedItem().toString());
            
            cliente.setNascimento(DateChecker(jFTnascimento.getText()));
            
            dao.add(cliente);
            jTnome.setText("");
            jTcpf.setText("");
            jTrg.setText("");
            jTcelular.setText("");
            jTtelefone.setText("");
            jTemail.setText("");
            jTendereco.setText("");
            jTbairro.setText("");
            jTcidade.setText("");
            jTendereco.setText("");
            jFTnascimento.setText("");
            JOptionPane.showMessageDialog(null, "Cliente cadastrado!");
        }
    }//GEN-LAST:event_jBcadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcadastrar;
    private javax.swing.JComboBox jCbEstado;
    private javax.swing.JFormattedTextField jFTnascimento;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLRG;
    private javax.swing.JLabel jLUF;
    private javax.swing.JLabel jLbairro;
    private javax.swing.JLabel jLcell;
    private javax.swing.JLabel jLcidade;
    private javax.swing.JLabel jLemail;
    private javax.swing.JLabel jLendereco;
    private javax.swing.JLabel jLnasc;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLtele;
    private javax.swing.JLabel jLtitle;
    private javax.swing.JPanel jPnContato;
    private javax.swing.JPanel jPnDados;
    private javax.swing.JPanel jPnEndereco;
    private javax.swing.JPanel jPnPrincipal;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JTextField jTcelular;
    private javax.swing.JTextField jTcidade;
    private javax.swing.JTextField jTcpf;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTendereco;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTrg;
    private javax.swing.JTextField jTtelefone;
    // End of variables declaration//GEN-END:variables
}
