/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.VendaDAO;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import util.ValidaCPF;
/**
 *
 * @author USER
 */
public class Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Vendas() {
        try {
            this.setIconImage(ImageIO.read(new File("img/venda.png")));
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        jTcpf.setText(ValidaCPF.imprimeCPF(Main.cliente.getCPF()));
        jTnome.setText(Main.cliente.getNome());
        jTrg.setText(Main.cliente.getRG());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnPrincipal = new javax.swing.JPanel();
        jLtitle = new javax.swing.JLabel();
        jPnDados = new javax.swing.JPanel();
        jLnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLCPF = new javax.swing.JLabel();
        jTcpf = new javax.swing.JTextField();
        jLRG = new javax.swing.JLabel();
        jTrg = new javax.swing.JTextField();
        jPnVenda = new javax.swing.JPanel();
        jLcell = new javax.swing.JLabel();
        jTvalor = new javax.swing.JTextField();
        jLproduto = new javax.swing.JLabel();
        jTproduto = new javax.swing.JTextField();
        jLpagto = new javax.swing.JLabel();
        jLvencimento = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jCbMetodo = new javax.swing.JComboBox();
        jLparcelas = new javax.swing.JLabel();
        jTparcelas = new javax.swing.JTextField();
        jTvencimento = new javax.swing.JTextField();
        jTdata = new javax.swing.JTextField();
        jLvalorP = new javax.swing.JLabel();
        jTvalorP = new javax.swing.JTextField();
        jBvender = new javax.swing.JButton();

        setTitle("Registro de Vendas");

        jPnPrincipal.setBackground(new java.awt.Color(56, 56, 56));

        jLtitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLtitle.setText("TryFatus");
        jLtitle.setForeground(new Color(187,187,187));

        jPnDados.setBackground(new java.awt.Color(56, 56, 56));
        jPnDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new Font("Times New Roman", 1, 14), new Color(187,187,187)));
        jPnDados.setForeground(new java.awt.Color(56, 56, 56));
        jPnDados.setToolTipText("");

        jLnome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLnome.setForeground(new Color(187,187,187));
        jLnome.setText("Nome:");

        jTnome.setEditable(false);
        jTnome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTnome.setSelectionColor(new java.awt.Color(0, 0, 0));
        jTnome.setBackground(new Color(69,73,74));
        jTnome.setForeground(new Color(187, 187, 187));

        jLCPF.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLCPF.setForeground(new Color(187,187,187));
        jLCPF.setText("CPF:");

        jTcpf.setEditable(false);
        jTcpf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTcpf.setBackground(new Color(69,73,74));
        jTcpf.setForeground(new Color(187, 187, 187));

        jLRG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLRG.setForeground(new Color(187,187,187));
        jLRG.setText("RG:");

        jTrg.setEditable(false);
        jTrg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTrg.setBackground(new Color(69,73,74));
        jTrg.setForeground(new Color(187, 187, 187));

        javax.swing.GroupLayout jPnDadosLayout = new javax.swing.GroupLayout(jPnDados);
        jPnDados.setLayout(jPnDadosLayout);
        jPnDadosLayout.setHorizontalGroup(
            jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCPF)
                    .addComponent(jLnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPnDadosLayout.createSequentialGroup()
                        .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTrg, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTnome))
                .addGap(15, 15, 15))
        );
        jPnDadosLayout.setVerticalGroup(
            jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLCPF)
                        .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnVenda.setBackground(new java.awt.Color(56, 56, 56));
        jPnVenda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Venda", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new Font("Times New Roman", 1, 14), new Color(187,187,187)));

        jLcell.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLcell.setForeground(new Color(187,187,187));
        jLcell.setText("Valor:");

        jTvalor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTvalor.setBackground(new Color(69,73,74));
        jTvalor.setForeground(new Color(187, 187, 187));

        jLproduto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLproduto.setForeground(new Color(187,187,187));
        jLproduto.setText("Produto:");

        jTproduto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTproduto.setBackground(new Color(69,73,74));
        jTproduto.setForeground(new Color(187, 187, 187));

        jLpagto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLpagto.setText("Pagamento:");
        jLpagto.setForeground(new Color(187,187,187));

        jLvencimento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLvencimento.setText("Vencimento:");
        jLvencimento.setForeground(new Color(187,187,187));

        jLdata.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLdata.setText("Data:");
        jLdata.setForeground(new Color(187,187,187));

        jCbMetodo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCbMetodo.setMaximumRowCount(13);
        jCbMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A Vísta", "A Prazo" }));
        jCbMetodo.setToolTipText("");
        jCbMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbMetodoActionPerformed(evt);
            }
        });

        jLparcelas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLparcelas.setForeground(new Color(187,187,187));
        jLparcelas.setText("Parcelas:");

        jTparcelas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTparcelas.setText("1");
        jTparcelas.setEnabled(false);
        jTparcelas.setBackground(new Color(69,73,74));
        jTparcelas.setForeground(new Color(187, 187, 187));

        jTvencimento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTvencimento.setEnabled(false);
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            jTvencimento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }

        jTvencimento.setFont(new java.awt.Font("Times New Roman", 0, 14));

        jTvencimento.setBackground(new Color(69,73,74));

        jTvencimento.setForeground(new Color(187,187,187));
        jTvencimento.setEnabled(false);

        jTdata.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            jTdata = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }

        jTdata.setFont(new java.awt.Font("Times New Roman", 0, 14));

        jTdata.setBackground(new Color(69,73,74));

        jTdata.setForeground(new Color(187,187,187));
        LocalDate date = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        jTdata.setText(date.format(formatter));

        jLvalorP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLvalorP.setText("Valor Pago:");
        jLvalorP.setForeground(new Color(187,187,187));

        jTvalorP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTvalorP.setEnabled(false);
        jTvalorP.setBackground(new Color(69,73,74));
        jTvalorP.setForeground(new Color(187, 187, 187));

        jBvender.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jBvender.setText("Cadastrar Venda");
        jBvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnVendaLayout = new javax.swing.GroupLayout(jPnVenda);
        jPnVenda.setLayout(jPnVendaLayout);
        jPnVendaLayout.setHorizontalGroup(
            jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnVendaLayout.createSequentialGroup()
                        .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPnVendaLayout.createSequentialGroup()
                                .addComponent(jLproduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTproduto))
                            .addGroup(jPnVendaLayout.createSequentialGroup()
                                .addComponent(jLcell)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLdata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTdata, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPnVendaLayout.createSequentialGroup()
                        .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPnVendaLayout.createSequentialGroup()
                                .addComponent(jLpagto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnVendaLayout.createSequentialGroup()
                                .addComponent(jLvencimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTvencimento)))
                        .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnVendaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLvalorP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTvalorP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPnVendaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLparcelas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPnVendaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jBvender)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPnVendaLayout.setVerticalGroup(
            jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLproduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdata)
                    .addComponent(jLcell)
                    .addComponent(jTdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnVendaLayout.createSequentialGroup()
                        .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTparcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLparcelas))
                            .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLpagto)
                                .addComponent(jCbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLvencimento)
                            .addComponent(jTvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnVendaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPnVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLvalorP)
                            .addComponent(jTvalorP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBvender)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPnPrincipalLayout = new javax.swing.GroupLayout(jPnPrincipal);
        jPnPrincipal.setLayout(jPnPrincipalLayout);
        jPnPrincipalLayout.setHorizontalGroup(
            jPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPnDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPnPrincipalLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLtitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnPrincipalLayout.setVerticalGroup(
            jPnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvenderActionPerformed
        // TODO add your handling code here:
        if (jTproduto.getText().isEmpty() || jTvalor.getText().isEmpty() || jTparcelas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Produto,  Valor e Parcelas não podem estar vazios!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            model.Venda venda = new model.Venda();
            venda.setCliente(Main.cliente.getCPF());
            if (jCbMetodo.getSelectedItem().toString().equals("A Vísta")) {
                venda.setAtiva(0);
            } else if (Double.parseDouble(jTvalorP.getText()) >= Double.parseDouble(jTvalor.getText())) {
                venda.setAtiva(0);
            } else {
                venda.setAtiva(1);
            }
            venda.setMetodo(jCbMetodo.getSelectedItem().toString());
            venda.setData(util.DateChecker.DateChecker(jTdata.getText()));
            venda.setVencimento(util.DateChecker.DateChecker(jTvencimento.getText()));
            venda.setProduto(jTproduto.getText());
            venda.setParcelas(Integer.parseInt(jTparcelas.getText()));
            venda.setValor(Double.parseDouble(jTvalor.getText()));
            venda.setPago(jCbMetodo.getSelectedItem().toString().equals("A Vísta") ? Double.parseDouble(jTvalor.getText()) : Double.parseDouble(jTvalorP.getText()));
            VendaDAO.add(venda);
            //
            jTvalor.setText("");
            jTproduto.setText("");
            jTparcelas.setText("");
            jTvencimento.setText("");
            jCbMetodo.setSelectedItem("A Vísta");
            jTparcelas.setText("1");
            JOptionPane.showMessageDialog(null, "Venda registrada.");
        }
    }//GEN-LAST:event_jBvenderActionPerformed

    private void jCbMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbMetodoActionPerformed
        // TODO add your handling code here:
        if (jCbMetodo.getSelectedItem().equals("A Vísta")) {
            jTparcelas.setText("1");
            jTparcelas.setEnabled(false);
            jTvalorP.setEnabled(false);
            jTvencimento.setEnabled(false);
        } 
        if (jCbMetodo.getSelectedItem().equals("A Prazo")) {
            jTparcelas.setEnabled(true);
            jTvalorP.setEnabled(true);
            jTvencimento.setEnabled(true);
        }
    }//GEN-LAST:event_jCbMetodoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBvender;
    private javax.swing.JComboBox jCbMetodo;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLRG;
    private javax.swing.JLabel jLcell;
    private javax.swing.JLabel jLdata;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLpagto;
    private javax.swing.JLabel jLparcelas;
    private javax.swing.JLabel jLproduto;
    private javax.swing.JLabel jLtitle;
    private javax.swing.JLabel jLvalorP;
    private javax.swing.JLabel jLvencimento;
    private javax.swing.JPanel jPnDados;
    private javax.swing.JPanel jPnPrincipal;
    private javax.swing.JPanel jPnVenda;
    private javax.swing.JTextField jTcpf;
    private javax.swing.JTextField jTdata;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTparcelas;
    private javax.swing.JTextField jTproduto;
    private javax.swing.JTextField jTrg;
    private javax.swing.JTextField jTvalor;
    private javax.swing.JTextField jTvalorP;
    private javax.swing.JTextField jTvencimento;
    // End of variables declaration//GEN-END:variables
}
